/**
 * Scenery Module Constants
 * Centralized location for all magic strings, numbers, and configuration values
 */

/** Module identifier used throughout Foundry VTT */
export const MODULE_ID = 'scenery';

/** Flag key used to store scenery data in scene documents */
export const FLAG_KEY = 'data';

/** Icon classes used in the UI */
export const ICONS = {
  APP: 'fas fa-images',
  PREVIEW: 'fa fa-eye',
  DELETE: 'fa fa-trash',
  ADD: 'fa fa-plus',
  SCAN: 'fas fa-search',
  OK: 'fa fa-check',
  COPY: 'fa fa-copy',
  RESET: 'fa fa-undo',
  HAS_DATA: 'fa fa-check-circle',
  INFO: 'fa fa-info-circle',
  LIGHTBULB: 'fa fa-lightbulb',
  VOLUME: 'fa fa-volume-up',
  TILES: 'fa fa-th',
  WALLS: 'fa fa-vector-square',
  DRAWINGS: 'fa fa-pencil-alt',
  TEMPLATES: 'fa fa-ruler-combined',
  REGIONS: 'fa fa-draw-polygon',
  NOTES: 'fa fa-bookmark',
  CLEAR: 'fa fa-trash',
  CANCEL: 'fa fa-times',
} as const;

/** Variation names and defaults */
export const VARIATIONS = {
  DEFAULT_NAME: 'Default',
} as const;

/** Window/dialog configuration */
export const WINDOW = {
  WIDTH: 900,
  HEIGHT: 'auto',
  MIN_HEIGHT_CONTENT: 300,
  MIN_HEIGHT_WINDOW: 350,
  MAX_HEIGHT_WINDOW: '80vh',
  MAX_HEIGHT_TABLE: '60vh',
  ICON: 'fas fa-images',
  CLASSES: ['scenery'],
} as const;

/** Settings keys */
export const SETTINGS = {
  DEBUG_LOGGING: 'debugLogging',
  GLOBAL_LIGHTS: 'globalLights',
  GLOBAL_SOUNDS: 'globalSounds',
  GLOBAL_TILES: 'globalTiles',
  GLOBAL_WALLS: 'globalWalls',
  GLOBAL_DRAWINGS: 'globalDrawings',
  GLOBAL_TEMPLATES: 'globalTemplates',
  GLOBAL_REGIONS: 'globalRegions',
  GLOBAL_NOTES: 'globalNotes',
  SHOW_VARIATIONS_LABEL: 'showVariationsLabel',
  SHOW_HEADER_BUTTON: 'showHeaderButton',
  GM_MAP_IDENTIFIERS: 'gmMapIdentifiers',
  PLAYER_MAP_IDENTIFIERS: 'playerMapIdentifiers',
} as const;

/** CSS Selectors used in the UI */
export const SELECTORS = {
  BUTTON_FILE_PICKER: 'button.file-picker',
  INPUT_TEXT: 'input[type="text"]',
} as const;

/** Template paths */
export const TEMPLATES = {
  SCENERY: '/modules/scenery/templates/scenery.hbs',
  VARIATION: '/modules/scenery/templates/variation.hbs',
  COPY_DIALOG: '/modules/scenery/templates/copy-dialog.hbs',
  FOOTER: 'templates/generic/form-footer.hbs',
} as const;

/** Button labels (i18n keys) */
export const I18N_KEYS = {
  APP_NAME: 'SCENERY.APP_NAME',
  BUTTON_SCAN: 'SCENERY.BUTTON_SCAN',
  BUTTON_ADD: 'SCENERY.BUTTON_ADD',
  BUTTON_OK: 'SCENERY.BUTTON_OK',
  BUTTON_COPY: 'SCENERY.BUTTON_COPY',
  BUTTON_CANCEL: 'SCENERY.BUTTON_CANCEL',
  LABEL_COPY: 'SCENERY.LABEL_COPY',
  COPY_SELECT_SOURCE: 'SCENERY.COPY_SELECT_SOURCE',
  COPY_SELECT_SOURCE_PLACEHOLDER: 'SCENERY.COPY_SELECT_SOURCE_PLACEHOLDER',
  COPY_SELECT_ELEMENTS: 'SCENERY.COPY_SELECT_ELEMENTS',
  ELEMENT_LIGHTS: 'SCENERY.ELEMENT_LIGHTS',
  ELEMENT_SOUNDS: 'SCENERY.ELEMENT_SOUNDS',
  ELEMENT_TILES: 'SCENERY.ELEMENT_TILES',
  ELEMENT_WALLS: 'SCENERY.ELEMENT_WALLS',
  SELECT_ALL: 'SCENERY.SELECT_ALL',
  SELECT_NONE: 'SCENERY.SELECT_NONE',
  ERROR_SELECTION: 'SCENERY.ERROR_SELECTION',
  ERROR_COPY_DEFAULT: 'SCENERY.ERROR_COPY_DEFAULT',
  ERROR_NO_SELECTION: 'SCENERY.ERROR_NO_SELECTION',
  ERROR_NO_SOURCE: 'SCENERY.ERROR_NO_SOURCE',
  SUCCESS_COPY: 'SCENERY.SUCCESS_COPY',
  LOADING: 'SCENERY.LOADING',
  SETTING_DEBUG_LOGGING: 'SCENERY.SETTING_DEBUG_LOGGING',
  SETTING_DEBUG_LOGGING_HINT: 'SCENERY.SETTING_DEBUG_LOGGING_HINT',
  SETTING_SHOW_VARIATIONS: 'SCENERY.SETTING_SHOW_VARIATIONS',
  SETTING_SHOW_VARIATIONS_HINT: 'SCENERY.SETTING_SHOW_VARIATIONS_HINT',
  SETTING_SHOW_HEADER_BUTTON: 'SCENERY.SETTING_SHOW_HEADER_BUTTON',
  SETTING_SHOW_HEADER_BUTTON_HINT: 'SCENERY.SETTING_SHOW_HEADER_BUTTON_HINT',
  SETTING_GLOBAL_LIGHTS: 'SCENERY.SETTING_GLOBAL_LIGHTS',
  SETTING_GLOBAL_LIGHTS_HINT: 'SCENERY.SETTING_GLOBAL_LIGHTS_HINT',
  SETTING_GLOBAL_SOUNDS: 'SCENERY.SETTING_GLOBAL_SOUNDS',
  SETTING_GLOBAL_SOUNDS_HINT: 'SCENERY.SETTING_GLOBAL_SOUNDS_HINT',
  SETTING_GLOBAL_TILES: 'SCENERY.SETTING_GLOBAL_TILES',
  SETTING_GLOBAL_TILES_HINT: 'SCENERY.SETTING_GLOBAL_TILES_HINT',
  SETTING_GLOBAL_WALLS: 'SCENERY.SETTING_GLOBAL_WALLS',
  SETTING_GLOBAL_WALLS_HINT: 'SCENERY.SETTING_GLOBAL_WALLS_HINT',
  SETTING_GLOBAL_DRAWINGS: 'SCENERY.SETTING_GLOBAL_DRAWINGS',
  SETTING_GLOBAL_DRAWINGS_HINT: 'SCENERY.SETTING_GLOBAL_DRAWINGS_HINT',
  SETTING_GLOBAL_TEMPLATES: 'SCENERY.SETTING_GLOBAL_TEMPLATES',
  SETTING_GLOBAL_TEMPLATES_HINT: 'SCENERY.SETTING_GLOBAL_TEMPLATES_HINT',
  SETTING_GLOBAL_REGIONS: 'SCENERY.SETTING_GLOBAL_REGIONS',
  SETTING_GLOBAL_REGIONS_HINT: 'SCENERY.SETTING_GLOBAL_REGIONS_HINT',
  SETTING_GLOBAL_NOTES: 'SCENERY.SETTING_GLOBAL_NOTES',
  SETTING_GLOBAL_NOTES_HINT: 'SCENERY.SETTING_GLOBAL_NOTES_HINT',
  SETTING_GM_MAP_IDENTIFIERS: 'SCENERY.SETTING_GM_MAP_IDENTIFIERS',
  SETTING_GM_MAP_IDENTIFIERS_HINT: 'SCENERY.SETTING_GM_MAP_IDENTIFIERS_HINT',
  SETTING_PLAYER_MAP_IDENTIFIERS: 'SCENERY.SETTING_PLAYER_MAP_IDENTIFIERS',
  SETTING_PLAYER_MAP_IDENTIFIERS_HINT: 'SCENERY.SETTING_PLAYER_MAP_IDENTIFIERS_HINT',
  SETTING_GLOBAL_RESET: 'SCENERY.SETTING_GLOBAL_RESET',
  SETTING_GLOBAL_RESET_DONE: 'SCENERY.SETTING_GLOBAL_RESET_DONE',
  BUTTON_ABOUT: 'SCENERY.BUTTON_ABOUT',
  ABOUT_TITLE: 'SCENERY.ABOUT_TITLE',
} as const;
